import { HEMA_001_BUNDLED_PDF, HEMA_001_TEMPLATE_ID } from '@/lib/fillable-pdf/schema';
import type { FillablePdfTemplate } from '@/types/modules';

/** Bundled demo template used before migration 040 is applied or when DB is empty. */
export const BUNDLED_HEMA_001_TEMPLATE: FillablePdfTemplate = {
  id: HEMA_001_TEMPLATE_ID,
  title: 'Routine Tests Form',
  formNumber: 'Form-Hema-001',
  description: 'Hematology Section routine tests manual form with PDF overlay fields.',
  version: 1,
  status: 'draft',
  sourcePdfPath: HEMA_001_BUNDLED_PDF,
  sourcePdfName: 'Form-Hema-001-Routine-Tests-Form.pdf',
  pageCount: 1,
  pageWidthPt: 612,
  pageHeightPt: 790.95,
  isPublished: false,
  createdBy: '',
  createdAt: new Date(0).toISOString(),
  updatedAt: new Date(0).toISOString(),
  fields: [
    { id: 'f1', fieldKey: 'patient_name', label: 'Patient Name', type: 'text', pageNumber: 1, posX: 0.188, posY: 0.164, width: 0.286, height: 0.020, required: true, config: { fontSize: 9 } },
    { id: 'f2', fieldKey: 'clinic', label: 'Clinic', type: 'text', pageNumber: 1, posX: 0.580, posY: 0.164, width: 0.359, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f3', fieldKey: 'gender_age', label: 'Gender / Age', type: 'text', pageNumber: 1, posX: 0.237, posY: 0.186, width: 0.212, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f4', fieldKey: 'ref_by', label: 'Ref. By', type: 'text', pageNumber: 1, posX: 0.580, posY: 0.186, width: 0.359, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f5', fieldKey: 'patient_id', label: 'Patient ID', type: 'text', pageNumber: 1, posX: 0.237, posY: 0.206, width: 0.212, height: 0.020, required: true, config: { fontSize: 9 } },
    { id: 'f6', fieldKey: 'received_on', label: 'Received On', type: 'date', pageNumber: 1, posX: 0.629, posY: 0.206, width: 0.294, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f7', fieldKey: 'esr_result', label: 'ESR Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.266, width: 0.106, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f8', fieldKey: 'esr_remarks', label: 'ESR Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.266, width: 0.172, height: 0.020, required: false, config: { fontSize: 8 } },
    { id: 'f9', fieldKey: 'malaria_result', label: 'Malaria Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.297, width: 0.106, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f10', fieldKey: 'malaria_remarks', label: 'Malaria Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.297, width: 0.172, height: 0.020, required: false, config: { fontSize: 8 } },
    { id: 'f11', fieldKey: 'sickle_result', label: 'Sickle Test Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.326, width: 0.106, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f12', fieldKey: 'sickle_remarks', label: 'Sickle Test Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.326, width: 0.172, height: 0.020, required: false, config: { fontSize: 8 } },
    { id: 'f13', fieldKey: 'pt_result', label: 'PT Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.377, width: 0.106, height: 0.048, required: false, config: { fontSize: 9 } },
    { id: 'f14', fieldKey: 'pt_remarks', label: 'PT Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.377, width: 0.172, height: 0.048, required: false, config: { fontSize: 8 } },
    { id: 'f15', fieldKey: 'inr_result', label: 'INR Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.428, width: 0.106, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f16', fieldKey: 'inr_remarks', label: 'INR Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.428, width: 0.172, height: 0.020, required: false, config: { fontSize: 8 } },
    { id: 'f17', fieldKey: 'ptt_result', label: 'PTT Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.466, width: 0.106, height: 0.048, required: false, config: { fontSize: 9 } },
    { id: 'f18', fieldKey: 'ptt_remarks', label: 'PTT Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.466, width: 0.172, height: 0.048, required: false, config: { fontSize: 8 } },
    { id: 'f19', fieldKey: 'ddimer_result', label: 'D-Dimer Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.516, width: 0.106, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f20', fieldKey: 'ddimer_remarks', label: 'D-Dimer Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.516, width: 0.172, height: 0.020, required: false, config: { fontSize: 8 } },
    { id: 'f21', fieldKey: 'fibrinogen_result', label: 'Fibrinogen Result', type: 'text', pageNumber: 1, posX: 0.253, posY: 0.550, width: 0.106, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f22', fieldKey: 'fibrinogen_remarks', label: 'Fibrinogen Remarks', type: 'text', pageNumber: 1, posX: 0.792, posY: 0.550, width: 0.172, height: 0.020, required: false, config: { fontSize: 8 } },
    { id: 'f23', fieldKey: 'blood_film', label: 'Blood Film', type: 'textarea', pageNumber: 1, posX: 0.237, posY: 0.592, width: 0.703, height: 0.082, required: false, config: { fontSize: 8, multiline: true } },
    { id: 'f24', fieldKey: 'body_fluid', label: 'Body Fluid', type: 'textarea', pageNumber: 1, posX: 0.237, posY: 0.678, width: 0.703, height: 0.101, required: false, config: { fontSize: 8, multiline: true } },
    { id: 'f25', fieldKey: 'technical_verification', label: 'Technical Verification', type: 'text', pageNumber: 1, posX: 0.327, posY: 0.782, width: 0.155, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f26', fieldKey: 'technical_verification_date', label: 'Technical Verification Date', type: 'auto_date', pageNumber: 1, posX: 0.188, posY: 0.807, width: 0.196, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f27', fieldKey: 'technical_verification_time', label: 'Technical Verification Time', type: 'auto_time', pageNumber: 1, posX: 0.188, posY: 0.830, width: 0.196, height: 0.020, required: false, config: { fontSize: 9 } },
    { id: 'f28', fieldKey: 'received_by', label: 'Received By', type: 'staff_identity', pageNumber: 1, posX: 0.654, posY: 0.782, width: 0.245, height: 0.020, required: false, config: { fontSize: 9, autoFill: 'staff_name' } },
    { id: 'f29', fieldKey: 'received_by_date', label: 'Received By Date', type: 'auto_date', pageNumber: 1, posX: 0.588, posY: 0.807, width: 0.196, height: 0.020, required: false, config: { fontSize: 9, autoFill: 'received_by' } },
    { id: 'f30', fieldKey: 'received_by_time', label: 'Received By Time', type: 'auto_time', pageNumber: 1, posX: 0.588, posY: 0.830, width: 0.196, height: 0.020, required: false, config: { fontSize: 9, autoFill: 'received_by' } },
  ],
};
