export const PERMISSIONS_LIST = [
  'users.manage', 'roles.manage', 'settings.manage', 'audit.view',
  'reports.view', 'reports.approve', 'reports.manage', 'kpi.view', 'kpi.manage',
  'employees.view', 'employees.manage', 'employees.evaluate',
  'tasks.view', 'tasks.manage', 'tasks.approve',
  'instruments.view', 'instruments.manage',
  'maintenance.view', 'maintenance.manage', 'maintenance.perform',
  'qc.view', 'qc.manage',
  'critical_values.view', 'critical_values.manage', 'critical_values.review',
  'sample_rejections.view', 'sample_rejections.manage', 'sample_rejections.review',
  'corrected_results.view', 'corrected_results.manage',
  'tat.view', 'tat.manage',
  'training.view', 'training.manage',
  'documents.view', 'documents.manage',
  'inventory.view', 'inventory.manage',
  'meetings.view', 'meetings.manage',
  'risk.view', 'risk.manage',
  'capa.view', 'capa.manage',
  'notifications.view', 'notifications.manage',
  'media.view', 'media.manage',
  'forms.view', 'forms.manage',
  'announcements.view', 'announcements.manage',
  'calendar.view', 'calendar.manage',
  'report_builder.view', 'report_builder.manage',
] as const;
